# Configuration du serveur
spring.application.name=service-voiture
server.port=8084

# Configuration Eureka (si utilisé)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Configuration Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logs
logging.level.com.example.voiture=DEBUG